---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary
  namespace: hm
  labels:
    app: dictionary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary
  template:
    metadata:
      labels:
        app: dictionary
    spec:
      containers:
        - name: dictionary
          image: k8sland/go-dictionary-svc:0.0.1
          imagePullPolicy: IfNotPresent
          command: ["/app/dictionary"]
          args: ["-a", "assets", "-d", "trump.txt"]
          ports:
            - name: http
              containerPort: 4000
          resources: <!!CHANGE_ME!!>
          livenessProbe: <!!CHANGE_ME!!>
          readinessProbe: <!!CHANGE_ME!!>
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: dictionary
  namespace: hm
spec:
  type: ClusterIP
  selector:
    app: dictionary
  ports:
    - name: http
      port: 4000
---
# HPA
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dictionary
  namespace: hm
spec:
  scaleTargetRef:
    apiVersion: <!!CHANGE_ME!!>
    kind: <!!CHANGE_ME!!>
    name: <!!CHANGE_ME!!>
  minReplicas: <!!CHANGE_ME!!>
  maxReplicas: <!!CHANGE_ME!!>
  metrics:
    - type: Resource
      resource:
        name: <!!CHANGE_ME!!>
        target:
          type: <!!CHANGE_ME!!>
          averageUtilization: <!!CHANGE_ME!!>
