---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <!!CHANGE_ME!!>
  namespace: <!!CHANGE_ME!!>
  labels: <!!CHANGE_ME!!>
spec:
  replicas: <!!CHANGE_ME!!>
  selector: <!!CHANGE_ME!!>
  template:
    metadata:
      labels: <!!CHANGE_ME!!>
    spec:
      containers:
        - name: <!!CHANGE_ME!!>
          image: <!!CHANGE_ME!!>
          imagePullPolicy: <!!CHANGE_ME!!>
          command: <!!CHANGE_ME!!>
          args: <!!CHANGE_ME!!>
          ports:
            - name: <!!CHANGE_ME!!>
              containerPort: <!!CHANGE_ME!!>

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: <!!CHANGE_ME!!>
  namespace: <!!CHANGE_ME!!>
spec:
  type: <!!CHANGE_ME!!>
  selector: <!!CHANGE_ME!!>
  ports:
    - name: <!!CHANGE_ME!!>
      port: <!!CHANGE_ME!!>
