---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangman
  namespace: hm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangman
  template:
    metadata:
      labels:
        app: hangman
    spec:
      containers:
        - name: hangman
          image: k8sland/go-hangman-svc:0.0.1
          imagePullPolicy: IfNotPresent
          command: ["/app/hangman"]
          args: ["-d", "dictionary:4000"]
          ports:
            - name: http
              containerPort: 5000

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: hangman
  namespace: hm
  labels:
    app: hangman
spec:
  type: NodePort
  selector:
    app: hangman
  ports:
    - name: http
      port: 5000
      targetPort: http
      nodePort: 30500
