---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary
  namespace: hm
  labels:
    app: dictionary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary
  template:
    metadata:
      labels:
        app: dictionary
    spec:
      containers:
        - name: dictionary
          image: k8sland/go-dictionary-svc:0.0.1
          imagePullPolicy: IfNotPresent
          command: ["/app/dictionary"]
          args: ["-a", "assets", "-d", "trump.txt"]
          ports:
            - name: http
              containerPort: 4000
          resources:
            requests:
              cpu: 100m
              memory: 10Mi
            limits:
              cpu: 200m
              memory: 20Mi
          livenessProbe:
            httpGet:
              path: /api/v1/alive
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/v1/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: dictionary
  namespace: hm
spec:
  type: ClusterIP
  selector:
    app: dictionary
  ports:
    - name: http
      port: 4000
---
# HPA
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dictionary
  namespace: hm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dictionary
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 5Mi
