---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangman
  namespace: hm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangman
  template:
    metadata:
      labels:
        app: hangman
    spec:
      containers:
        - name: hangman
          image: k8sland/go-hangman-svc:0.0.1
          imagePullPolicy: IfNotPresent
          command: ["/app/hangman"]
          args: ["-d", "dictionary:4000"]
          ports:
            - name: http
              containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 10Mi
            limits:
              cpu: 200m
              memory: 20Mi
          livenessProbe:
            httpGet:
              path: /api/v1/alive
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 2
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/v1/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: hangman
  namespace: hm
  labels:
    app: hangman
spec:
  type: NodePort
  selector:
    app: hangman
  ports:
    - name: http
      port: 5000
      targetPort: http
      nodePort: 30500
---
# HPA
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hangman
  namespace: hm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hangman
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
