---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangman
  namespace: hm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangman
  template:
    metadata:
      labels:
        app: hangman
    spec:
      containers:
        - name: hangman
          image: k8sland/go-hangman-svc:0.0.1
          imagePullPolicy: IfNotPresent
          command: ["/app/hangman"]
          args: ["-d", "dictionary:4000"]
          ports:
            - name: http
              containerPort: 5000
          resources: <!!CHANGE_ME!!>
          livenessProbe: <!!CHANGE_ME!!>
          readinessProbe: <!!CHANGE_ME!!>
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: hangman
  namespace: hm
  labels:
    app: hangman
spec:
  type: NodePort
  selector:
    app: hangman
  ports:
    - name: http
      port: 5000
      targetPort: http
      nodePort: 30500
---
# HPA
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hangman
  namespace: hm
spec:
  scaleTargetRef:
    apiVersion: <!!CHANGE_ME!!>
    kind: <!!CHANGE_ME!!>
    name: <!!CHANGE_ME!!>
  minReplicas: <!!CHANGE_ME!!>
  maxReplicas: <!!CHANGE_ME!!>
  metrics:
    - type: Resource
      resource:
        name: <!!CHANGE_ME!!>
        target:
          type: <!!CHANGE_ME!!>
          averageUtilization: <!!CHANGE_ME!!>
